rtl8723au: Fix smatch errors and warnings in os_dep/ioctl_linux.c
Smatch lists the following:
  CHECK   /home/finger/rtl8723au/os_dep/ioctl_linux.c
/home/finger/rtl8723au/os_dep/ioctl_linux.c:1632 rtw_wx_get_range() warn: assigning (-78) to unsigned variable 'range->avg_qual.level'
/home/finger/rtl8723au/os_dep/ioctl_linux.c:5122 rtw_p2p_get_invitation_procedure() warn: should this be a bitwise op?
/home/finger/rtl8723au/os_dep/ioctl_linux.c:6320 rtw_p2p_get2() warn: statement has no effect 5
/home/finger/rtl8723au/os_dep/ioctl_linux.c:6603 rtw_dbg_port() warn: unsigned 'extra_arg' is never less than zero.
/home/finger/rtl8723au/os_dep/ioctl_linux.c:7493 set_group_key() warn: missing break? reassigning 'keylen'
/home/finger/rtl8723au/os_dep/ioctl_linux.c:9936:24: error: bad constant expression
/home/finger/rtl8723au/os_dep/ioctl_linux.c:10115:24: error: bad constant expression
/home/finger/rtl8723au/os_dep/ioctl_linux.c:10233:35: error: bad constant expression
/home/finger/rtl8723au/os_dep/ioctl_linux.c:10265:35: error: bad constant expression
/home/finger/rtl8723au/os_dep/ioctl_linux.c:10314:35: error: bad constant expression
/home/finger/rtl8723au/os_dep/ioctl_linux.c:10340:35: error: bad constant expression
/home/finger/rtl8723au/os_dep/ioctl_linux.c:10380:35: error: bad constant expression
/home/finger/rtl8723au/os_dep/ioctl_linux.c:10565:28: error: bad constant expression
/home/finger/rtl8723au/os_dep/ioctl_linux.c:10612:35: error: bad constant expression
/home/finger/rtl8723au/os_dep/ioctl_linux.c:10731:35: error: bad constant expression
/home/finger/rtl8723au/os_dep/ioctl_linux.c:10929:27: error: bad constant expression
/home/finger/rtl8723au/os_dep/ioctl_linux.c:10953:33: error: bad constant expression
/home/finger/rtl8723au/os_dep/ioctl_linux.c:10982:33: error: bad constant expression
/home/finger/rtl8723au/os_dep/ioctl_linux.c:11023:35: error: bad constant expression

Several of these are real errors in the code.

Signed-off-by: Larry Finger <Larry.Finger@lwfinger.net>